version: "3.7"
services:
  opentelemetry-collector:
    image: codeboten/collector:0.45.0
    volumes:
      - ./collector-config.yml:/etc/opentelemetry-collector.yml
    command:
      - "--config=/etc/opentelemetry-collector.yml"
    ports:
      - 4317:4317
      - 4318:4318
      - 13133:13133
      - 8889:8889
  jaeger:
    image: jaegertracing/all-in-one:1.29.0
    ports:
      - 6831:6831/udp
      - 16686:16686
  rust-api:
    build:
      context: ./rust-api/
    ports:
      - 9005:8080
  dotnet-api:
    build:
      context: ./dotnet-api/
    ports:
      - 9006:80
